In [6]:
import pandas as pd

In [7]:
import matplotlib.pyplot as plt

In [8]:
import numpy as np

In [9]:
df=pd.read_csv("HR_Analytics_Raw.csv", sep=",")

In [10]:
df

,Employee_ID,First_Name,Last_Name,Gender,Age,Department,Job_Role,Education,Education_Field,Marital_Status,...,Work_Life_Balance,Training_Hours,Overtime,Remote_Work,Promotion_Last_5_Years,Attrition,Absent_Days,Manager_Rating,City,State
0,EMP100002,Vikram,Sharma,Female,48.0,IT,Executive,Master,Business,Married,...,5.0,76,Yes,No,No,No,21,NaN,Pune,MH
1,EMP100003,Vikram,Gupta,male,44.0,Operations,Analyst,MBA,Arts,Single,...,5.0,6,No,Yes,No,Yes,17,3.0,Indore,MP
2,EMP100004,Ananya,Gupta,F,21.0,Finance,Intern,MBA,Engineering,Married,...,2.0,57,No,No,No,No,18,1.0,Delhi,Delhi
3,EMP100005,Nishtha,Gupta,M,41.0,Sales,Associate,Master,Science,NaN,...,1.0,34,No,No,Yes,No,22,3.0,Bhopal,MP
4,EMP100006,Vikram,Sharma,NaN,55.0,Operations,Executive,MBA,Engineering,Married,...,4.0,22,Yes,Yes,No,No,23,2.0,Bhopal,MP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,EMP119997,Vikram,Sharma,male,36.0,Finance,Associate,Bachelor,Arts,Married,...,4.0,37,NaN,Yes,No,No,10,NaN,Bhopal,MP
19996,EMP119998,Priya,Sharma,NaN,41.0,Operations,Manager,Master,Business,Married,...,3.0,55,NaN,Yes,No,No,23,1.0,Pune,MH
19997,EMP119999,Vikram,Singh,M,49.0,Finance,Manager,Bachelor,Arts,Married,...,2.0,16,NaN,No,Yes,No,11,NaN,Indore,MP
19998,EMP120000,Vikram,Iyer,M,27.0,Finance,Executive,PhD,Arts,Divorced,...,NaN,33,Yes,No,No,Yes,22,3.0,Bhopal,MP
19999,EMP120001,Priya,Patel,M,51.0,Human Resources,Manager,MBA,Business,Married,...,5.0,2,Yes,No,Yes,Yes,8,2.0,Bhopal,MP

In [11]:
df.head(10)

,Employee_ID,First_Name,Last_Name,Gender,Age,Department,Job_Role,Education,Education_Field,Marital_Status,...,Work_Life_Balance,Training_Hours,Overtime,Remote_Work,Promotion_Last_5_Years,Attrition,Absent_Days,Manager_Rating,City,State
0,EMP100002,Vikram,Sharma,Female,48.0,IT,Executive,Master,Business,Married,...,5.0,76,Yes,No,No,No,21,NaN,Pune,MH
1,EMP100003,Vikram,Gupta,male,44.0,Operations,Analyst,MBA,Arts,Single,...,5.0,6,No,Yes,No,Yes,17,3.0,Indore,MP
2,EMP100004,Ananya,Gupta,F,21.0,Finance,Intern,MBA,Engineering,Married,...,2.0,57,No,No,No,No,18,1.0,Delhi,Delhi
3,EMP100005,Nishtha,Gupta,M,41.0,Sales,Associate,Master,Science,NaN,...,1.0,34,No,No,Yes,No,22,3.0,Bhopal,MP
4,EMP100006,Vikram,Sharma,NaN,55.0,Operations,Executive,MBA,Engineering,Married,...,4.0,22,Yes,Yes,No,No,23,2.0,Bhopal,MP
5,EMP100007,Priya,Sharma,NaN,58.0,IT,Executive,Bachelor,Business,Single,...,NaN,16,No,Yes,No,Yes,26,3.0,Pune,MH
6,EMP100008,Nishtha,Gupta,Female,120.0,IT,Manager,PhD,Business,Single,...,5.0,52,No,Yes,Yes,Yes,8,3.0,Pune,MH
7,EMP100009,Ananya,Patel,NaN,50.0,Finance,Analyst,Bachelor,Science,Single,...,5.0,73,NaN,No,No,No,13,2.0,Delhi,Delhi
8,EMP100010,Rahul,Gupta,Female,42.0,IT,Executive,PhD,Arts,NaN,...,5.0,80,NaN,No,No,No,17,5.0,Pune,MH
9,EMP100011,Priya,Iyer,NaN,37.0,Operations,Associate,Bachelor,Science,NaN,...,4.0,11,Yes,Yes,Yes,Yes,26,2.0,Bhopal,MP

In [12]:
df.tail(10)

,Employee_ID,First_Name,Last_Name,Gender,Age,Department,Job_Role,Education,Education_Field,Marital_Status,...,Work_Life_Balance,Training_Hours,Overtime,Remote_Work,Promotion_Last_5_Years,Attrition,Absent_Days,Manager_Rating,City,State
19990,EMP119992,Nishtha,Singh,male,120.0,IT,Associate,PhD,Business,Divorced,...,2.0,76,NaN,No,No,Yes,22,5.0,Indore,MP
19991,EMP119993,Ananya,Iyer,F,47.0,Operations,Analyst,PhD,Engineering,NaN,...,NaN,20,No,Yes,No,Yes,17,NaN,Delhi,Delhi
19992,EMP119994,Rahul,Gupta,Male,26.0,HR,Executive,MBA,Arts,NaN,...,2.0,64,Yes,No,Yes,No,28,2.0,Indore,MP
19993,EMP119995,Priya,Iyer,NaN,50.0,HR,Associate,PhD,Arts,Married,...,3.0,38,NaN,No,No,Yes,5,5.0,Bhopal,MP
19994,EMP119996,Aarav,Singh,male,42.0,Finance,Manager,MBA,Engineering,Married,...,1.0,55,NaN,Yes,No,Yes,29,2.0,Delhi,Delhi
19995,EMP119997,Vikram,Sharma,male,36.0,Finance,Associate,Bachelor,Arts,Married,...,4.0,37,NaN,Yes,No,No,10,NaN,Bhopal,MP
19996,EMP119998,Priya,Sharma,NaN,41.0,Operations,Manager,Master,Business,Married,...,3.0,55,NaN,Yes,No,No,23,1.0,Pune,MH
19997,EMP119999,Vikram,Singh,M,49.0,Finance,Manager,Bachelor,Arts,Married,...,2.0,16,NaN,No,Yes,No,11,NaN,Indore,MP
19998,EMP120000,Vikram,Iyer,M,27.0,Finance,Executive,PhD,Arts,Divorced,...,NaN,33,Yes,No,No,Yes,22,3.0,Bhopal,MP
19999,EMP120001,Priya,Patel,M,51.0,Human Resources,Manager,MBA,Business,Married,...,5.0,2,Yes,No,Yes,Yes,8,2.0,Bhopal,MP

In [13]:
df.columns

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Gender', 'Age', 'Department',
       'Job_Role', 'Education', 'Education_Field', 'Marital_Status',
       'Hire_Date', 'Years_at_Company', 'Salary', 'Bonus',
       'Performance_Rating', 'Job_Satisfaction', 'Work_Life_Balance',
       'Training_Hours', 'Overtime', 'Remote_Work', 'Promotion_Last_5_Years',
       'Attrition', 'Absent_Days', 'Manager_Rating', 'City', 'State'],
      dtype='str')

In [14]:
df.shape

(20000, 26)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Employee_ID             20000 non-null  str
 1   First_Name              20000 non-null  str
 2   Last_Name               20000 non-null  str
 3   Gender                  16666 non-null  str
 4   Age                     19581 non-null  float64
 5   Department              20000 non-null  str
 6   Job_Role                20000 non-null  str
 7   Education               20000 non-null  str
 8   Education_Field         20000 non-null  str
 9   Marital_Status          15046 non-null  str
 10  Hire_Date               20000 non-null  str
 11  Years_at_Company        20000 non-null  int64
 12  Salary                  20000 non-null  str
 13  Bonus                   14967 non-null  float64
 14  Performance_Rating      16603 non-null  float64
 15  Job_Satisfaction        16741 non-null  float64
 16  Work_Life_Balance       16704 non-null  float64
 17  Training_Hours          20000 non-null  int64
 18  Overtime                13361 non-null  str
 19  Remote_Work             20000 non-null  str
 20  Promotion_Last_5_Years  20000 non-null  str
 21  Attrition               20000 non-null  str
 22  Absent_Days             20000 non-null  int64
 23  Manager_Rating          16643 non-null  float64
 24  City                    20000 non-null  str
 25  State                   20000 non-null  str
dtypes: float64(6), int64(3), str(17)
memory usage: 4.0 MB

In [16]:
df.columns=(df.columns
            .str.strip()
            .str.lower()
            .str.replace(" ","_")
)

In [17]:
df.columns

Index(['employee_id', 'first_name', 'last_name', 'gender', 'age', 'department',
       'job_role', 'education', 'education_field', 'marital_status',
       'hire_date', 'years_at_company', 'salary', 'bonus',
       'performance_rating', 'job_satisfaction', 'work_life_balance',
       'training_hours', 'overtime', 'remote_work', 'promotion_last_5_years',
       'attrition', 'absent_days', 'manager_rating', 'city', 'state'],
      dtype='str')

In [18]:
df.isnull().sum()

employee_id                  0
first_name                   0
last_name                    0
gender                    3334
age                        419
department                   0
job_role                     0
education                    0
education_field              0
marital_status            4954
hire_date                    0
years_at_company             0
salary                       0
bonus                     5033
performance_rating        3397
job_satisfaction          3259
work_life_balance         3296
training_hours               0
overtime                  6639
remote_work                  0
promotion_last_5_years       0
attrition                    0
absent_days                  0
manager_rating            3357
city                         0
state                        0
dtype: int64

In [19]:
missing_percentage=(df.isnull().sum()/len(df))*100
missing_percentage

employee_id                0.000
first_name                 0.000
last_name                  0.000
gender                    16.670
age                        2.095
department                 0.000
job_role                   0.000
education                  0.000
education_field            0.000
marital_status            24.770
hire_date                  0.000
years_at_company           0.000
salary                     0.000
bonus                     25.165
performance_rating        16.985
job_satisfaction          16.295
work_life_balance         16.480
training_hours             0.000
overtime                  33.195
remote_work                0.000
promotion_last_5_years     0.000
attrition                  0.000
absent_days                0.000
manager_rating            16.785
city                       0.000
state                      0.000
dtype: float64

In [20]:
missing=df.isnull().sum()
missing=missing[missing>0]
missing.sort_values(ascending=False)

overtime              6639
bonus                 5033
marital_status        4954
performance_rating    3397
manager_rating        3357
gender                3334
work_life_balance     3296
job_satisfaction      3259
age                    419
dtype: int64

In [21]:
missing_summary=pd.DataFrame({
    "missing_count":df.isnull().sum(),
    "missing_percentage":df.isnull().sum()/len(df)*100
})
missing_summary=missing_summary[missing_summary['missing_count']>0]
missing_summary.sort_values(by="missing_percentage",ascending=False)

                    missing_count  missing_percentage
overtime                     6639              33.195
bonus                        5033              25.165
marital_status               4954              24.770
performance_rating           3397              16.985
manager_rating               3357              16.785
gender                       3334              16.670
work_life_balance            3296              16.480
job_satisfaction             3259              16.295
age                           419               2.095

In [22]:
df_raw=df.copy()

In [23]:
df['gender'].unique()

<StringArray>
['Female', 'male', 'F', 'M', nan, 'Male']
Length: 6, dtype: str

In [24]:
df["gender"].value_counts(dropna=False)

gender
Female    3389
male      3385
F         3380
NaN       3334
M         3292
Male      3220
Name: count, dtype: int64

In [25]:
df['gender']=df['gender'].replace({
    "male":"Male",
    "F":"Female",
    "M":"Male",
    
})

In [26]:
df['gender'].unique()

<StringArray>
['Female', 'Male', nan]
Length: 3, dtype: str

In [27]:
df['gender']=df['gender'].fillna('Unknown')

In [28]:
df['gender'].unique()

<StringArray>
['Female', 'Male', 'Unknown']
Length: 3, dtype: str

In [29]:
df['age'].dtype

dtype('float64')

In [30]:
df["age"].describe()

count    19581.000000
mean        41.180890
std         17.539911
min         -5.000000
25%         30.000000
50%         40.000000
75%         51.000000
max        120.000000
Name: age, dtype: float64

In [31]:
df['age'].isnull().sum()

np.int64(419)

In [32]:
df.loc[(df['age']<18)|(df['age']>65),"age"]=np.nan

In [33]:
df['age'].isnull().sum()

np.int64(1260)

In [34]:
df['age']=df['age'].fillna(df['age'].median())

In [35]:
df['age'].describe()

count    20000.000000
mean        40.417150
std         11.186617
min         21.000000
25%         31.000000
50%         40.000000
75%         50.000000
max         60.000000
Name: age, dtype: float64

In [36]:
df['age'].isnull().sum()

np.int64(0)

In [37]:
df['marital_status'].unique()

<StringArray>
['Married', 'Single', nan, 'Divorced']
Length: 4, dtype: str

In [38]:
df['marital_status'].value_counts(dropna=False)

marital_status
Divorced    5064
Single      5007
Married     4975
NaN         4954
Name: count, dtype: int64

In [39]:
df['marital_status']=df['marital_status'].fillna('Unknown')

In [40]:
df['marital_status'].value_counts(dropna=False)

marital_status
Divorced    5064
Single      5007
Married     4975
Unknown     4954
Name: count, dtype: int64

In [41]:
df['salary'].dtype

In [42]:
df['salary'].isnull().sum()

np.int64(0)

In [43]:
df['salary']=(
    df['salary']
    .astype(str)
    
    .str.replace(",","",regex=False)
    .str.replace("₹","",regex=False)
    .str.strip()

    )

In [44]:
df['salary']=pd.to_numeric(df['salary'],errors="coerce")

In [45]:
df['salary'].describe()

count     20000.000000
mean      90157.109350
std       34704.196349
min       30005.000000
25%       59817.000000
50%       90448.000000
75%      120465.500000
max      149997.000000
Name: salary, dtype: float64

In [46]:
df['bonus'].dtype

dtype('float64')

In [47]:
df['bonus'].unique()[:20]

array([15000., 10000.,  5000.,    nan])

In [48]:
df['bonus'].isnull().sum()

np.int64(5033)

In [49]:
df['bonus'].head(50)

0     15000.0
1     10000.0
2      5000.0
3     10000.0
4     10000.0
5     15000.0
6     10000.0
7     15000.0
8     15000.0
9     10000.0
10    10000.0
11     5000.0
12        NaN
13    10000.0
14        NaN
15        NaN
16    15000.0
17    15000.0
18        NaN
19     5000.0
20     5000.0
21    15000.0
22     5000.0
23    10000.0
24    10000.0
25        NaN
26    15000.0
27    10000.0
28        NaN
29     5000.0
30     5000.0
31    10000.0
32    15000.0
33        NaN
34        NaN
35    10000.0
36        NaN
37     5000.0
38     5000.0
39        NaN
40    10000.0
41    15000.0
42    10000.0
43        NaN
44        NaN
45    15000.0
46    10000.0
47     5000.0
48        NaN
49        NaN
Name: bonus, dtype: float64

In [50]:
(df['bonus'].isnull().sum()/len(df)*100).round(2)

np.float64(25.16)

In [51]:
df[df["bonus"] == 0].shape[0]

0

In [52]:
df['bonus']=df['bonus'].fillna(0)

In [53]:
df['bonus'].isnull().sum()

np.int64(0)

In [54]:
df['bonus'].head(100)

0     15000.0
1     10000.0
2      5000.0
3     10000.0
4     10000.0
       ...
95    15000.0
96    15000.0
97    15000.0
98     5000.0
99    15000.0
Name: bonus, Length: 100, dtype: float64

In [55]:
df['performance_rating'].dtype

dtype('float64')

In [56]:
df['performance_rating'].value_counts(dropna=False)

performance_rating
NaN    3397
1.0    3392
5.0    3362
2.0    3333
3.0    3304
4.0    3212
Name: count, dtype: int64

In [57]:
df['performance_rating'] = df['performance_rating'].fillna(df['performance_rating'].median())

In [58]:
df['job_satisfaction'].dtype

dtype('float64')

In [59]:
df['job_satisfaction'].value_counts(dropna=False)

job_satisfaction
3.0    3412
2.0    3400
5.0    3340
4.0    3299
1.0    3290
NaN    3259
Name: count, dtype: int64

In [60]:
df['job_satisfaction'] = df['job_satisfaction'].fillna(df['job_satisfaction'].median())

In [61]:
df['job_satisfaction'].value_counts().sort_index()

job_satisfaction
1.0    3290
2.0    3400
3.0    6671
4.0    3299
5.0    3340
Name: count, dtype: int64

In [62]:
df['job_satisfaction'].isnull().sum()

np.int64(0)

In [63]:
df['work_life_balance'].dtype

dtype('float64')

In [64]:
df['work_life_balance'].value_counts(dropna=False).sort_index()

work_life_balance
1.0    3421
2.0    3320
3.0    3341
4.0    3277
5.0    3345
NaN    3296
Name: count, dtype: int64

In [65]:
df['work_life_balance']=df['work_life_balance'].fillna(df['work_life_balance'].median())

In [66]:
df['work_life_balance'].value_counts(dropna=False).sort_index()

work_life_balance
1.0    3421
2.0    3320
3.0    6637
4.0    3277
5.0    3345
Name: count, dtype: int64

In [67]:
df['training_hours'].dtype

dtype('int64')

In [68]:
df['training_hours'].describe()

count    20000.000000
mean        39.774500
std         23.345361
min          0.000000
25%         19.000000
50%         40.000000
75%         60.000000
max         80.000000
Name: training_hours, dtype: float64

In [69]:
df['training_hours'].isnull().sum()

np.int64(0)

In [70]:
df['absent_days'].dtype

dtype('int64')

In [71]:
df['absent_days'].describe()

count    20000.000000
mean        15.008750
std          8.960457
min          0.000000
25%          7.000000
50%         15.000000
75%         23.000000
max         30.000000
Name: absent_days, dtype: float64

In [72]:
df[(df["absent_days"]<0) | (df["absent_days"]>30)]

Empty DataFrame
Columns: [employee_id, first_name, last_name, gender, age, department, job_role, education, education_field, marital_status, hire_date, years_at_company, salary, bonus, performance_rating, job_satisfaction, work_life_balance, training_hours, overtime, remote_work, promotion_last_5_years, attrition, absent_days, manager_rating, city, state]
Index: []

[0 rows x 26 columns]

In [73]:
df['years_at_company'].dtype

dtype('int64')

In [74]:
df['years_at_company'].describe()

count    20000.000000
mean         9.985000
std          6.048455
min          0.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         20.000000
Name: years_at_company, dtype: float64

In [75]:
df['years_at_company'].isnull().sum()

np.int64(0)

In [76]:
df[(df['years_at_company']<0)|(df['years_at_company']>40)]

Empty DataFrame
Columns: [employee_id, first_name, last_name, gender, age, department, job_role, education, education_field, marital_status, hire_date, years_at_company, salary, bonus, performance_rating, job_satisfaction, work_life_balance, training_hours, overtime, remote_work, promotion_last_5_years, attrition, absent_days, manager_rating, city, state]
Index: []

[0 rows x 26 columns]

In [77]:
df['department'].dtype

In [78]:
df['department'].isnull().sum()

np.int64(0)

In [79]:
df['department'].unique()

<StringArray>
[             'IT',      'Operations',         'Finance',           'Sales',
 'Human Resources',              'HR',              'hr',       'Marketing']
Length: 8, dtype: str

In [80]:
df['department']=df['department'].str.strip().str.title()

In [81]:
df['department']=df['department'].replace({
    'hr':'HR',
    'Human Resources':'HR',
    'Hr':'HR',
    'It':'IT'
})

In [82]:
df['department'].unique()

<StringArray>
['IT', 'Operations', 'Finance', 'Sales', 'HR', 'Marketing']
Length: 6, dtype: str

In [83]:
df['department'].value_counts(dropna=False)

department
HR            7508
Sales         2570
Finance       2527
Operations    2516
Marketing     2455
IT            2424
Name: count, dtype: int64

In [84]:
df['education'].dtype

In [85]:
df['education'].unique()

<StringArray>
['Master', 'MBA', 'Bachelor', 'PhD']
Length: 4, dtype: str

In [86]:
df['education'].value_counts(dropna=False)

education
MBA         5113
Master      5000
PhD         4980
Bachelor    4907
Name: count, dtype: int64

In [87]:
df['education'].isnull().sum()

np.int64(0)

In [88]:
df['job_role'].dtype

In [89]:
df['job_role'].unique()

<StringArray>
['Executive', 'Analyst', 'Intern', 'Associate', 'Manager']
Length: 5, dtype: str

In [90]:
df['job_role'].value_counts(dropna=False)

job_role
Associate    4048
Intern       4019
Executive    4011
Manager      4007
Analyst      3915
Name: count, dtype: int64

In [91]:
df['job_role'].isnull().sum()

np.int64(0)

In [92]:
df['education_field'].unique()

<StringArray>
['Business', 'Arts', 'Engineering', 'Science']
Length: 4, dtype: str

In [93]:
df['education_field'].isnull().sum()

np.int64(0)

In [94]:
df['education_field'].value_counts(dropna=False)

education_field
Arts           5078
Business       5002
Engineering    4972
Science        4948
Name: count, dtype: int64

In [95]:
df['hire_date'].dtype

In [96]:
df['hire_date'].isnull().sum()

np.int64(0)

In [97]:
df['hire_date']=pd.to_datetime(df['hire_date'],errors='coerce',dayfirst=True,format="mixed")

In [98]:
df['hire_date'].dtype

dtype('<M8[us]')

In [99]:
df['hire_date'].isnull().sum()

np.int64(0)

In [100]:
df['hire_date'].head(20)

0    2020-10-08
1    2018-07-16
2    2019-12-23
3    2025-07-30
4    2021-01-08
5    2022-12-16
6    2022-10-30
7    2025-04-11
8    2023-11-05
9    2018-06-18
10   2025-06-25
11   2019-09-08
12   2015-02-03
13   2026-06-06
14   2025-10-02
15   2025-05-14
16   2025-07-05
17   2021-03-11
18   2023-01-10
19   2024-07-09
Name: hire_date, dtype: datetime64[us]

In [101]:
df['overtime'].dtype

In [102]:
df['overtime'].unique()

<StringArray>
['Yes', 'No', nan]
Length: 3, dtype: str

In [103]:
df['overtime'].value_counts(dropna=False)

overtime
No     6761
NaN    6639
Yes    6600
Name: count, dtype: int64

In [104]:
df['overtime']=df['overtime'].fillna('Not given')

In [105]:
df['overtime'].value_counts(dropna=False)

overtime
No           6761
Not given    6639
Yes          6600
Name: count, dtype: int64

In [106]:
df['remote_work'].dtype

In [107]:
df['remote_work'].value_counts(dropna=False)

remote_work
No     10001
Yes     9999
Name: count, dtype: int64

In [108]:
df['remote_work'].isnull().sum()

np.int64(0)

In [109]:
df['promotion_last_5_years'].dtype

In [110]:
df['promotion_last_5_years'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [111]:
df['promotion_last_5_years'].value_counts(dropna=False)

promotion_last_5_years
No     10178
Yes     9822
Name: count, dtype: int64

In [112]:
df['attrition'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [113]:
df['attrition'].value_counts(dropna=False)

attrition
Yes    10010
No      9990
Name: count, dtype: int64

In [114]:
df['attrition'].isnull().sum()

np.int64(0)

In [115]:
df['manager_rating'].dtype

dtype('float64')

In [116]:
df['manager_rating'].value_counts(dropna=False)

manager_rating
2.0    3374
5.0    3364
NaN    3357
1.0    3321
3.0    3298
4.0    3286
Name: count, dtype: int64

In [117]:
df['manager_rating']=df['manager_rating'].fillna(df['manager_rating'].median())

In [118]:
df['manager_rating'].value_counts(dropna=False)

manager_rating
3.0    6655
2.0    3374
5.0    3364
1.0    3321
4.0    3286
Name: count, dtype: int64

In [119]:
df['manager_rating'].isnull().sum()

np.int64(0)

In [120]:
df['city'].dtype

In [121]:
df['city'].unique()

<StringArray>
['Pune', 'Indore', 'Delhi', 'Bhopal', 'Jaipur']
Length: 5, dtype: str

In [122]:
df['city'].isnull().sum()

np.int64(0)

In [123]:
df['city'].value_counts(dropna=False)

city
Pune      4033
Bhopal    3999
Delhi     3998
Jaipur    3997
Indore    3973
Name: count, dtype: int64

In [124]:
df['state'].dtype

In [125]:
df['state'].unique()

<StringArray>
['MH', 'MP', 'Delhi', 'RJ']
Length: 4, dtype: str

In [126]:
df['state'].value_counts(dropna=False)

state
MP       7972
MH       4033
Delhi    3998
RJ       3997
Name: count, dtype: int64

In [127]:
df.to_csv("HR_CLEANED.csv",index=False)

EXPLORATORY DATA ANALYSIS:-

In [128]:
df.shape

(20000, 26)

In [129]:
df.head()

,employee_id,first_name,last_name,gender,age,department,job_role,education,education_field,marital_status,...,work_life_balance,training_hours,overtime,remote_work,promotion_last_5_years,attrition,absent_days,manager_rating,city,state
0,EMP100002,Vikram,Sharma,Female,48.0,IT,Executive,Master,Business,Married,...,5.0,76,Yes,No,No,No,21,3.0,Pune,MH
1,EMP100003,Vikram,Gupta,Male,44.0,Operations,Analyst,MBA,Arts,Single,...,5.0,6,No,Yes,No,Yes,17,3.0,Indore,MP
2,EMP100004,Ananya,Gupta,Female,21.0,Finance,Intern,MBA,Engineering,Married,...,2.0,57,No,No,No,No,18,1.0,Delhi,Delhi
3,EMP100005,Nishtha,Gupta,Male,41.0,Sales,Associate,Master,Science,Unknown,...,1.0,34,No,No,Yes,No,22,3.0,Bhopal,MP
4,EMP100006,Vikram,Sharma,Unknown,55.0,Operations,Executive,MBA,Engineering,Married,...,4.0,22,Yes,Yes,No,No,23,2.0,Bhopal,MP